process_group_id: "5b1c6c07-018e-1000-79a9-0539108347eb"
processGroupName: "Madhapur"
xPosition: 500
yPosition: 300

spring:
  application:
    name: "GenerateSQL"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/shop"
    username: "root"
    password: "root"
final_url: "http://localhost:38080/nifi-api/process-groups/"
processors:
  - name: InvokeHTTP Processor
    type: org.apache.nifi.processors.standard.InvokeHTTP
    position:
      x: 150
      y: 150
    config:
      properties:
        Remote URL: http://localhost:8099/newcompany
        HTTP Method: POST
        Output Response Regexp: (.*)
  - name: LogAttribute Processor
    type: org.apache.nifi.processors.standard.LogAttribute
    position:
      x: 350
      y: 150
    config: {}
